# Generated by Django 6.0 on 2025-12-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('forward', 'Forward Share'), ('reverse', 'Reverse Share')], max_length=10)),
                ('permission_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='sharing.fileresource')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_shares', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_shares', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('share_initiate', 'Share Initiated'), ('share_approve', 'Share Approved'), ('share_reject', 'Share Rejected'), ('share_revoke', 'Share Revoked'), ('permission_grant', 'Permission Granted (Mock Drive)'), ('permission_revoke', 'Permission Revoked (Mock Drive)')], db_index=True, max_length=30)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.fileresource')),
                ('share_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.sharerequest')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['owner', '-created_at'], name='file_resour_owner_i_92e759_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['file_id'], name='file_resour_file_id_02ebce_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerequest',
            index=models.Index(fields=['file', 'status'], name='share_reque_file_id_26353f_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerequest',
            index=models.Index(fields=['recipient', 'status'], name='share_reque_recipie_a329e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerequest',
            index=models.Index(fields=['status', '-requested_at'], name='share_reque_status_6238ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharerequest',
            unique_together={('file', 'recipient', 'status')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-timestamp'], name='audit_logs_actor_i_9ecce2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'),
        ),
    ]
